package com.bookstore.entity;
// Generated 13.Au.2019 21:05:13 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId implements java.io.Serializable {

	private Integer order›d;
	private Integer book›d;
	private int quantity;
	private double subtotal;

	public OrderDetailId() {
	}

	public OrderDetailId(int quantity, double subtotal) {
		this.quantity = quantity;
		this.subtotal = subtotal;
	}

	public OrderDetailId(Integer order›d, Integer book›d, int quantity, double subtotal) {
		this.order›d = order›d;
		this.book›d = book›d;
		this.quantity = quantity;
		this.subtotal = subtotal;
	}

	@Column(name = "order_id")
	public Integer getOrder›d() {
		return this.order›d;
	}

	public void setOrder›d(Integer order›d) {
		this.order›d = order›d;
	}

	@Column(name = "book_id")
	public Integer getBook›d() {
		return this.book›d;
	}

	public void setBook›d(Integer book›d) {
		this.book›d = book›d;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "subtotal", nullable = false, precision = 17, scale = 17)
	public double getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(double subtotal) {
		this.subtotal = subtotal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetailId))
			return false;
		OrderDetailId castOther = (OrderDetailId) other;

		return ((this.getOrder›d() == castOther.getOrder›d()) || (this.getOrder›d() != null
				&& castOther.getOrder›d() != null && this.getOrder›d().equals(castOther.getOrder›d())))
				&& ((this.getBook›d() == castOther.getBook›d()) || (this.getBook›d() != null
						&& castOther.getBook›d() != null && this.getBook›d().equals(castOther.getBook›d())))
				&& (this.getQuantity() == castOther.getQuantity()) && (this.getSubtotal() == castOther.getSubtotal());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrder›d() == null ? 0 : this.getOrder›d().hashCode());
		result = 37 * result + (getBook›d() == null ? 0 : this.getBook›d().hashCode());
		result = 37 * result + this.getQuantity();
		result = 37 * result + (int) this.getSubtotal();
		return result;
	}

}
